project: 
  type: website
  pre-render: quarto render --profile slides

logo: img/
website:
  title: "Computo workshop"
  navbar:
    left:
      - href: index.qmd
        text: Site
      - href: _slides/index.html
        text: Slides
    right: 
      - icon: github
        href: https://github.com/computorg/jds2025-workshop-template

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters: 
  - filters/unclutter.lua