project: 
  type: website
  render: 
    - index.qmd
  # post-render: rm -rf docs-resources/Slides/docs docs-resources/Slides/docs-resources
  output-dir: _slides
  resources:
    - "figures/*.svg"


footer: <https://computo.sfds.asso.fr>
logo: img/logo_text_vertical.png
date: last-modified
date-format: long
lang: en
format: 
  revealjs:
    width: 1240
    height: 700
    self-contained: true
    scrollable: false
    theme: [default, ./computo.scss]
    slide-number: true
    smaller: true
    title-slide-attributes:
      data-background-image: img/logo_text_vertical.png
      data-background-size: 18%
      data-background-position: top 25px left	25px
    preview-links: auto
bibliography: references.bib
csl: journal-of-open-research-software.csl
editor:
  render-on-save: true
slide-level: 2