profile:
  default: slides

bibliography: references.bib
csl: journal-of-open-research-software.csl

title: "Workshop on Reproducible Research"
subtitle: "A hands-on introduction to quarto with a Computo submission"
date: "2024-05-31"

footer: <https://computo.sfds.asso.fr>
logo: img/logo_text_vertical.svg
date-format: long
lang: en

authors:
  - name: Julien Chiquet
    email: julien.chiquet@inrae.fr
    affiliations:
      - INRAE, MIA-Paris
  - name: Pierre Neuvial
    email: Pierre.Neuvial@math.univ-toulouse.fr
    affiliations:
      - CNRS, IMT
      - Université de Toulouse
  - name: Ghislain Durif
    email: ghislain.durif@ens-lyon.fr
    affiliations:
      - CNRS
      - ENS Lyon, LBMC
  - name: Tanguy Lefort
    email: tanguy.lefort@umontpellier.fr
    affiliations:
      - Université de Montpellier, IMAG
      - CNRS, Inria, LIRMM
  - name: François-David Collin
    email: francois-david.collin@umontpellier.fr
    affiliations:
      - CNRS
      - IMAG
