project: 
  type: website

website:
  title: "Computo workshop"
  navbar:
    left:
      - href: index.qmd
        text: Site
      - href: _slides/index.html
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters: 
  - filters/unclutter.lua